### ISSUE TITLE
command_output

### ISSUE THREAD

**Issue by avonderluft** [mattbrictson/airbrussh#104]
In my deploy.rb I'm setting command_output to false, but everything still show on the console.
```   
set :log_level, :info
set :format_options, command_output: false, log_file: "deploy_logs/deploying.log"
```

**Comment by avonderluft** [comment]
In fact it doesn't seem to matter what I set the command_output to.  Also tried :stderr

**Comment by avonderluft** [comment]
guess I should move this over to capistrano repo...

**Comment by mattbrictson** [comment]
Actually yes, this is the appropriate repo for this issue.

**Comment by mattbrictson** [comment]
Thanks for the report. Can you paste an example of the console output that is not being hidden?

**Comment by avonderluft** [comment]
https://gist.github.com/avonderluft/a4a93c1fa852cd87c9cbdd592f50b85e

**Comment by mattbrictson** [comment]
Thanks for providing the gist. It looks to me that airbrussh is working as intended. Let me clarify:

If you disable command output in airbrussh, you should *still* see:

1. Names of tasks
2. Which commands are being run
3. When each command completes
4. Any explicit logging messages

You will *not* see any command output. This means stdout and stderr data from the remote commands themselves.

For example, for this command:

```
00:01 git:check
      01 git ls-remote https://******:******@github.com/projectdx/unicorn.git HEAD
```

That `git ls-remote` command normally produces output on `stdout`. But because of the airbrussh setting, that output is not being shown. So in this case it appears to be working as expected.

I don't know what is causing these messages:

```
avonderluft.dev.renewfund.com: copying overrides...
```

I assume they are explicit logging messages, and not command output. In that case it would make sense that they are being displayed.

If you don't want to see any output from Capistrano at all, then `:command_output` is not the appropriate setting. You should disable airbrussh altogether, by replacing it with a different formatter like `:blackhole` which hides everything or `:dot` which shows only a dot per command.

```ruby
set :format, :blackhole # or :dot
```

That is documented here: https://github.com/capistrano/sshkit#output-handling

Does that clear things up, or is there still a bug here that I missed?

Also, if you see an opportunity to improve the documentation to make behavior more obvious, please let us know.

**Comment by avonderluft** [comment]
ok.  Is it possible to use :blackhole or :dot and still get the verbose out logged to file?

Also, I used to be able to change error level mid-deploy to suppress display of creds:
```
      default_log_level = fetch(:log_level)
      before "git:check", :set_log_error do
        SSHKit.config.output_verbosity = :error
      end
      before "git:create_release", :set_log_default do
        SSHKit.config.output_verbosity = default_log_level
      end
```
This does not seem to work with airbrussh

**Comment by mattbrictson** [comment]
No, airbrussh does not honor the `log_level` setting. It is kind of its own thing.

If you want to mute the console output but still log everything to a file, could you just use output redirection, like this?

```
cap production deploy &> deploy_logs/deploying.log
```

**Comment by avonderluft** [comment]
sounds good.  thanks for your help.
