### ISSUE TITLE
Out-of-line require statement

### ISSUE THREAD

**Issue by vassilevsky** [mattbrictson/airbrussh#5]
Hello :)

First of all, I have to say that this library is a real gem! ;) Adding it to my projects at the moment.

While doing so, I noticed the require statement:

```ruby
require "airbrussh/capistrano"
```

But AFAIK all other Capistrano plugins follow the reverse pattern:

```ruby
require "capistrano/rbenv"
require "capistrano/bundler"
require "capistrano/rails"
...
```

It seems that this gem will be better if it's rearranged to allow the same require pattern:

```ruby
require "capistrano/airbrussh"
```

<3

**Comment by mattbrictson** [comment]
Good observation! I went back and forth on this one.

`airbrussh/capistrano` is the more "Ruby" way to do it. Airbrussh is the name of the gem, so it makes sense for it to also be the top-level namespace. By this reasoning "capistrano" is a specialized subset of what the airbrussh gem offers.

I agree that `capistrano/airbrussh` is more in line with other capistrano require statements. However, the examples you've given are all gems where the actual name of the gem is `capistrano-*`, e.g. `capistrano-rbenv`. So here again, the require statement is consistent with the gem name.

If I had named the gem `capistrano-airbrussh`, then the `capistrano/airbrussh` require statement would definitely make sense. However I wanted airbrussh to be usable outside of capistrano (i.e. with sshkit directly).

**Comment by mattbrictson** [comment]
I'll leave this issue open in case other people want to weigh in on the discussion.

**Comment by carlesso** [comment]
Just my 2 cents. I agree with @mattbrictson, also because all the gems you've nominates actually are from the capistrano community itself: https://github.com/capistrano

In my humble opinion, only gems from capistrano organization (let's call them official) should have the `capistrano/whatever` format, while any external contribution should go under `whatherver/whatever2`, and if whatever2 is capistrano is just easy to remember.

**Comment by mattbrictson** [comment]
I'm considering this issue settled for now.
