### ISSUE TITLE
Refactor to remove Airbrussh::Colors in favor of SSHKit::Color

### ISSUE THREAD

**Issue by mattbrictson** [mattbrictson/airbrussh#63]
We have some duplication between Airbrussh and SSHKit in terms of the colorization code. Is there a nice way to consolidate this code for the simplification of both projects?

This is a continuation of the discussion started here: https://github.com/capistrano/capistrano/issues/1509#issuecomment-151458350

@robd I took a look at this last night, and immediately I ran into some difficulty. Airbrussh and SSHKit approach colorization from opposite directions: Airbrussh applies colors regardless, and then strips the ANSI color escape codes conditionally during output (in `Console`); SSHKit applies colors conditionally, based on the output of the formatter.

I'm not sure if either approach is necessarily better, but they are at odds. Do you have any ideas of how to approach it?

**Comment by robd** [comment]
I'm not sure - my gut feeling is that it's simpler not to add the colors in the first place if they are not needed, but perhaps this has downsides I haven't thought of.

One difference is that in the SSHKit approach, colors wouldn't be stripped from output of other commands called by SSHKit. I can't work out if this is a benefit or disadvantage. If I understand correctly, Airbrussh's `config.color = false` option strips the colors from the output of commands run by SSHKit. This could be useful if users want the formatter to do this but I'm not sure if that is a common use case. 

The [changes I made recently](https://github.com/capistrano/sshkit/pull/246) continue to allow SSHKit users to force colors to be on, but do not to force them to be off. Since these haven't been released I'm not sure if there are use cases where users want to be able to force the colors to be off even though their output has a tty associated with it. Personally I would be in favour of adding support for the [Airbrussh color config options](https://github.com/mattbrictson/airbrussh/blob/72dca97ab79defad4b568118672efd31a0d42f15/lib/airbrussh/console.rb#L69-L78) to SSHKit. This was disussed a bit here: https://github.com/capistrano/sshkit/issues/245, but things have moved on quite a bit, so maybe worth discussing again.

If we did add that new option, then in a future major release I would like to remove [this colorize override in the `SimpleTextFormatter`](https://github.com/capistrano/sshkit/blob/e06d6b8424979a6a3a2974f375490d2aa15c2ac4/lib/sshkit/formatters/simple_text.rb#L8-L10). This would leave a method - `format_message` on the `SimpleTextFormatter. I think this could be reimplemented as 2 config options on the `Pretty` formatter: 

1) Whether to show the command UUID 
2) Whether to show the log level prefix (eg INFO, WARN etc)

The `SimpleTextFormatter` output is the same as the pretty formatter, but with each of these components omitted.

I realise all of this isn't really helping with the mission of making Airbrussh the default Capistrano formatter, but I think, if it makes sense, it would be good if Airbrussh could be configured by using the same options as SSHKit.

If we wanted to reuse the SSHKit color support, then one approach would be to use the [colorize method from the abstract formatter](https://github.com/capistrano/sshkit/blob/e06d6b8424979a6a3a2974f375490d2aa15c2ac4/lib/sshkit/formatters/abstract.rb#L12), but without adding support for `config.color = :true | :false | :auto`, this would be a retrograde step for Airbrussh I guess.

I'm not sure if this helps at all? :(

**Comment by mattbrictson** [comment]
I don't think this refactor is necessary. Sharing the `Colors` implementation between SSHKit and Capistrano further couples the internals of the two gems, with not much benefit.
