### ISSUE TITLE
Allow tasks to not use airbrussh formatting, when verbose output is wanted

### ISSUE THREAD

**Issue by maxigs** [mattbrictson/airbrussh#69]
Loving the extension, but unfortunately i had to deactivate it because the nice formatting kills one capistrano task i use often.

I usuall have a task to tail logs on the server, like so (maybe also for other log types):

    desc 'Logs'
    task :logs do
      on roles(:app) do
        execute "tail -f #{fetch(:deploy_to)}/shared/log/#{fetch(:rails_env)}.log"
      end
    end

Which is a very simple way to help debugging issues on a server environment. Unfortunately it also uses the pretty formatting and thus not giving any output anymore.

I could not find any way of turning formatting of for just a single task. Maybe i missed it, otherwise i think it would be a great addition, not only so i can turn the whole airbrussh on again :)

**Comment by mattbrictson** [comment]
As mentioned in the [FAQ](https://github.com/mattbrictson/airbrussh#faq), you can enable command output in order to see the tail output. However this enables output for *all* commands. It sounds like that's not what you want.

This is not elegant, but one thing you could try is to edit your task to enable output within the task:

```ruby
desc 'Logs'
task :logs do
  Airbrussh.configuration.command_output = true
  on roles(:app) do
    execute "tail -f #{fetch(:deploy_to)}/shared/log/#{fetch(:rails_env)}.log"
  end
end
```

**Comment by mattbrictson** [comment]
Not making any promises, but what do you think about being able to control output task by task in the configuration like this?

```ruby
Airbrussh.configure do |config|
  config.command_output = {
    :default => false, # Disable output for all tasks by default
    :logs => true,     # Enable for the :logs task,
    :deploy => true,   # Enable for any task in the :deploy namespace,
    /tail/ => true,    # Enable for any task name containing "tail"
  }
end

**Comment by maxigs** [comment]
Hi, thanks for getting back so fast :-)

I was testing it with 

    desc 'Logs'
    task :logs do
      set :format, :pretty
      on roles(:app) do
        execute "tail -f #{fetch(:deploy_to)}/shared/log/#{fetch(:rails_env)}.log"
      end
    end

but had no luck.

I don't really need anything fancy here, your first example (i did not try it yet) would be perfectly fine, not sure if a too complicated configuration is worth the effort for the few cases when its needed.

Haven't had a deep look into your code yet so i'm not sure if it makes sense but how about something like allowing:

    execute "some command", output_formatting: false

**Comment by mattbrictson** [comment]
`set :format` will not work, because the `:format` value is only used once, when Capistrano starts up. If you change the value later it has no effect.

`execute "some command", output_formatting: false` could be made to work, but it would be an option that only Airbrussh understands. I don't think it is a good idea to complicate the `execute` API just for Airbrussh. That's my gut reaction.

However `Airbrussh.configuration.command_output = true` within your task should do the trick. Let me know if it works.

**Comment by maxigs** [comment]
Putting `Airbrussh.configuration.command_output = true` into the task seems to work perfectly. Thanks a lot! :)

**Comment by mattbrictson** [comment]
Great! I'll consider this issue closed, unless there is a strong need for a more full-fledged solution.
